sudo : required
services :
  - docker
  
  
before_install :
  - docker build -t 270808/react-test -f ./client/Dockerfile.dev .


script:
  - docker run -e CI=true 270808/react-test npm test -- --coverage

after_success:
  - docker build -t 270808/multi-client  ./client
  - docker build -t 270808/multi-nginx  ./nginx
  - docker build -t 270808/multi-server  ./server
  - docker build -t 270808/multi-worker  ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  - docker push 270808/multi-client
  - docker push 270808/multi-nginx
  - docker push 270808/multi-server
  - docker push 270808/multi-worker